### ISSUE TITLE
How can we leverage the whole screen using tailwind?

### ISSUE THREAD

**Issue by Natim** [sebsheep/foobarctory#4]
For now the dashboard is set on the left of the screen with robots vertically added to the left as a column. How can we make it a dashboard with data more visible and actionable?

![image](https://user-images.githubusercontent.com/229453/89987844-fa352b80-dc7e-11ea-9625-7780885ae1f5.png)

**Comment by sebsheep** [comment]
Tailwind nearly reflects css properties. The doc is good, it has a nice "search feature tool bar": http://tailwindcss.com/ .

We could use something like `HA.class "flex flex-row flex-wrap"` for the robots' container to make the robots stake horizontally until they can no more (we'll have kind of a grid of robots).

**Comment by Natim** [comment]
If you feel like making a proposal about that.

I had in mind a dashboard inspired by this look and feel: 
![image](https://user-images.githubusercontent.com/229453/90000908-0d50f700-dc91-11ea-8b28-160283eb7737.png)
![image](https://user-images.githubusercontent.com/229453/90001064-41c4b300-dc91-11ea-98cc-45db08b3e713.png)

**Comment by sebsheep** [comment]
I've pushed something in the taste of the first image. I've also initialize 10 robots at the beginning in order to show how the scrolling works.

**Comment by Natim** [comment]
Oh great ! Is it possible to make it a bit responsive when we resize the window?

![image](https://user-images.githubusercontent.com/229453/90020193-d0e0c380-dcaf-11ea-90bf-fa57ce47855b.png)
